### ISSUE TITLE
Handle 401 responses

### ISSUE THREAD

**Issue by Nash0x7E2** [juntofoundation/junto-mobile#1021]
The app currently does not handle 401 errors sent back from the server.

### Expected Behaviour
- If a token exists, try reauthenticating the user 
- If the token is expired, log the user out then prompt them to sign in once again

**Comment by jdeepee** [comment]
Does the first bullet point have the intention to use a refresh token to re-auth the user?

**Comment by Nash0x7E2** [comment]
@jdeepee That was the original idea, however, after looking at the Cognito docs, refreshing of the access token is done by the library. Unfortunately, when the refresh token expires, the user must sign in again to obtain a new one. 

Created a PR for this here #1023
