### ISSUE TITLE
Several relations issues

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1031]
- Disconnecting with someone while they are in your pack doesn't allow you to reinvite them into your pack
- Notification of someone inviting me to pack doesn't disappear after accepting

**Comment by jdeepee** [comment]
These should be resolved now; or at-least the second one is for sure.

For the first case I wrote a detailed test which is checking that the user is removed from the pack when dis-connected; this passed okay so I am pretty confident in this working.
