### ISSUE TITLE
Limited number of posts showing up in Subscriptions/Connections Perspective(s)

### ISSUE THREAD

**Issue by doraliliom** [juntofoundation/junto-mobile#1090]
When I go to my subscriptions/connections perspective(s) and I scroll down, I see only 29/28 posts and I am sure there should be more. 

I double checked my subscriptions and I am certain that I am subscribed to people whose posts do not show up under the given perspective(s).

**Comment by sunyatax** [comment]
Anyone else experiencing this? @jdeepee @fayeed @Nash0x7E2

**Comment by jdeepee** [comment]
I haven't seen any behavior like this. How many members do you have in these perspectives @doraliliom

**Comment by doraliliom** [comment]
Subscriptions: 78
Connections: 66
