### ISSUE TITLE
Mentions (and channels) UI optimizations

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1103]
Hey @fayeed, here are two things we can clean up:

1) After searching for users and going back to an empty search, the list retains the state of the previous state for a moment.

2) The ListView glitches in and out on every new search query. We should have some sort of backdrop that is the size of the list so the whole ListView doesn't look like it's fading in and out. I'll send you a video in slack.

**Comment by fayeed** [comment]
@sunyatax Hey, you could check the PR, although the fixes are only done for the long-form expressions.
