### ISSUE TITLE
Alphabetizing contacts

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1104]
@fayeed would be great if you could take a quick look at this as well. If you go to the drawer -> Invite, you'll see your contacts being rendered in the app. The sort function I have there now is not fully alphabetizing the list correctly though... can you fix this? Probably best to test on your device so you have more data.

**Comment by fayeed** [comment]
@sunyatax Can you give more context regarding this, I am currently using a Mac mini & don't have access to a USB hub to test it on my device.

**Comment by sunyatax** [comment]
It's just not fully sorting properly. Things are mostly alphabetical, meaning they are from A - Z but within each letter they're pretty random.
