### ISSUE TITLE
Refresh glitch in Den (we should see if this happens else where too)

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1122]

**Comment by fayeed** [comment]
@sunyatax I don't think this is a glitch, when you refresh it shows a loading indicator & then a loaded state, I think that it might be the server is closer to you or the internet is faster you only see the loading state for a fraction of a second and that might seems glitchy, but for my case, I see loading indicator for a proper 2 - 3 seconds before the data is loaded, let me know if this clears things up :).

**Comment by sunyatax** [comment]
Sending you a video of what I mean - the glitch is more of the feed disappearing and coming back in. This isn't the case with Collective expressions, though this may have to do with caching
