### ISSUE TITLE
Filter by channels via pressing hashtag

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1127]

**Comment by sunyatax** [comment]
@fayeed would be great if you could take care of this:

By default, pressing a channel should filter the Collective by that channel. We should see what context the user is in though, so if they are in a different perspective, like Subscriptions, Connections, or a custom one we should filter that perspective. Same goes for whether they're in a Pack.

While you get going on this, I'll rework the way people can manually filter (from side drawer -> modal bottom sheet)

**Comment by fayeed** [comment]
@sunyatax For this, we might need to make channels clickable in the list as well right? and also if someone clicks the channels it should move back to the perspective list right?

**Comment by sunyatax** [comment]
If someone is already in a feed, clicking a channel should just refresh that same feed (and not bring them back to the list of perspectives) but show them the perspective they were on. So if I was in my Subscriptions perspective and I press on a channel, it should show me by Subscriptions perspective filtered by the channel I clicked

**Comment by sunyatax** [comment]
Also, what list are you referring to exactly?

**Comment by fayeed** [comment]
@sunyatax the collective feed.

**Comment by sunyatax** [comment]
Hm, the Collective feed doesn't have a list of channels unless you're referring to the side drawer to filter. If so, ignore that because I'm in process of reworking it to a modal bottom sheet UI

**Comment by fayeed** [comment]
yes, for perspective feed do members need to go to the open view screen to filter by tapping on channels or they can just tap on the feed itself, like for example, mentions are not tappable in the feed.

**Comment by sunyatax** [comment]
Ah I see. Yeah, people should have to open the expression first before filtering by channel. Only exception is if it is a Comment Preview.
