### ISSUE TITLE
Mentions search

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1136]
Let's have the results from the API return users that have the characters in either their username or name when mentioning. Right now, we're only account for usernames.

**Comment by fayeed** [comment]
@sunyatax we are either passing `username` or `name` to query the members, not sure if we can do both at the same time from the API side, @jdeepee is it possible to do both?

**Comment by sunyatax** [comment]
Just checked with him and it's currently not possible, but AWS Neptune's Gremlin queries have improved so Josh is going to tackle this soon

**Comment by fayeed** [comment]
@sunyatax @jdeepee Any updates on the API I planning to take this up tomorrow if the API is done.

**Comment by jdeepee** [comment]
@fayeed might be able to get this today but no promises, lots of other stuff that also needs attention. Ill update on slack if I get it done. 

I guess you might even be able to develop this without the API piece in place. Response will be exactly as it is now; only difference is the request can contain both username & name at the same time.

**Comment by sunyatax** [comment]
This should be live in dev now @fayeed

**Comment by sunyatax** [comment]
Bump :) @fayeed
