### ISSUE TITLE
Complete push notifs

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1137]
@fayeed - Josh deployed push notifs to dev api. Can you test and make sure everything is working? We also need to configure this for prod as well... you should have access to the firebase console but lmk if you need anything else.

**Comment by sunyatax** [comment]
How are things going on this front @fayeed? Would be nice to ship this start of next week

**Comment by fayeed** [comment]
I haven't gotten the time to get to this yet & also not sure what to check to test

**Comment by sunyatax** [comment]
We just need to make sure that we're getting push notifs for each notification type (connection request, mention, comment -- etc. -- I'll send you the list) and then set up firebase for prod env as well

**Comment by sunyatax** [comment]
```
ConnectionRequest
    {
      'title': '',
      'body': '{username} sent you a connection request.',
    }
  GroupJoinRequest
    {
      'title': '',
      'body': '{username} invited you to their pack.',
    }
  Comment
    {
      'title': '',
      'body': '{username} commented on your expression.',
    } 
  
  Subscribe
    {
      'title': '',
      'body': '{username} subscribed to you.',
    }  
  Connection
    {
      'title': '',
      'body': '{username} is now your 1st degree connection.',
    }  
  PackRelation
    {
      'title': '',
      'body': '{username} accepted your pack invitation.',
    }  
  Mention
    {
      'title': '',
      'body': '{username} mentioned you in an expression.',
    }
```
