### ISSUE TITLE
Brotli compression

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1140]
@fayeed know much about implementing this?

**Comment by fayeed** [comment]
@sunyatax This needs to be implemented in the backend, and then from the app we just need to update an HTTP header with a new value `Accept-Encoding: br, gzip`, and that should be it. Although for Brotli to work we also need to get https working on the backend.

**Comment by sunyatax** [comment]
Got it. thanks - @jdeepee is working on implementing it in the backend
