### ISSUE TITLE
Hyperlinked text improvements 

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1154]
Hyperlink detection can be improved to handle a few more edge cases.

i.e...

1. Anything after https:// should be hyperlinked
2. Unique domains like .foundation should be accounted for

![Simulator Screen Shot - iPhone 11 - 2020-11-06 at 21 44 54](https://user-images.githubusercontent.com/37339459/98430330-88506080-207a-11eb-8471-748c5bdea84e.png)

**Comment by fayeed** [comment]
@sunyatax the regex I used accounts for 4-6 characters after `.`  maybe that's why.

**Comment by sunyatax** [comment]
@fayeed Looks like the https://{website} doesn't work when https is not all lowercase. I made a few posts in the dev environment with Https:// (capital H) so you can see what I mean.
