### ISSUE TITLE
Customize notifications

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1172]
We need to build a panel where users can customize which specific things they'd like to get notified for. Can you build a basic UI for this and integrate w the API? I can come in after and polish the design @fayeed

Should be a simple toggle on/off for each notification type with all of them being on by default.
```
/// Notification for a connection request
    ConnectionRequest,
    /// Notification for a new request to join a group
    GroupJoinRequest,
    /// Notification for a new comment on a post
    Comment,
    /// Notification for a new "follow" on user
    Subscribe,
    /// Notification for a newly accepted connection
    Connection,
    /// Notification for a new pack relationship
    PackRelation,
    /// Notification for a mention on an expression
    Mention,
```

**Comment by fayeed** [comment]
yeah can do, is the API up for this?

**Comment by sunyatax** [comment]
Yep dev API has this already
