### ISSUE TITLE
Redundant hero animation

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#509]
1. Add new photo expression to collective
2. Go to collective
3. Swipe to open right drawer
4. Go to My Den
5. Press back button
6. Observe hero animation from the first image in your den expressions feed to the first image in collective expression list

**Comment by Nash0x7E2** [comment]
Can this be closed? have not seen this in a while.

**Comment by orestesgaolin** [comment]
The issue still exists on Android

**Comment by orestesgaolin** [comment]
Now, when the images are larger than usual this problem is much more serious i.e. the app almost freezes for a brief moment

**Comment by orestesgaolin** [comment]
![20200508_103127](https://user-images.githubusercontent.com/16854239/81388183-3608a400-9118-11ea-92d8-bdf14642fd58.gif)

**Comment by sunyatax** [comment]
Yeah let's resolve this soon
