### ISSUE TITLE
Infinite loading and wrong backgrounds layout

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#601]
After upgrade to current version the app is loading infinitely. I was logged in few hours before. 

Also the background right edge is not shown.

Will try to debug it tomorrow.

**Comment by Nash0x7E2** [comment]
Is this on the latest dev? It could be that you don’t have the latest key. Will ping you on slack.

**Comment by orestesgaolin** [comment]
It's current build from codemagic. Previous one worked ok.

Dominik Roszkowski

sob., 2 maj 2020, 00:33 użytkownik Neevash Ramdial <notifications@github.com>
napisał:
