### ISSUE TITLE
Long s3 media load times

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#602]
Retrieving s3 files often takes several seconds or more

**Comment by Nash0x7E2** [comment]
I've seen this happening but only directly after a media expression has been created. 

On a cold boot of the app, the images typically load within a few seconds even on a restricted connection.

**Comment by jdeepee** [comment]
Yes this happens to me on a cold boot of the app also; if the app is not closed the s3 data remains cached. However the loading time for a cold boot seems very long; did something change with the compression of the files you send to s3? I don't think it was this long before

**Comment by Nash0x7E2** [comment]
The files are higher quality now, we don't do any compression client-side so it could be due to the large download size

**Comment by jdeepee** [comment]
Ah that's the problem I guess. I think these large files are also degrading the speed of the app. Clicking back when viewing one of these large file expressions results in a very low fps animation. 

Might be worth exploring some other compression methods. I know a little about video compression but not much about photo.

**Comment by Nash0x7E2** [comment]
Agreed, I am looking at image compression and there are a few Dart library which can handle this but I don't know much about video compression. We can discuss this more tomorrow during our dev call. 

Libs I am looking at 
- https://pub.dev/packages/flutter_luban
- https://pub.dev/packages/flutter_image_compress

**Comment by jdeepee** [comment]
Cool - another option which could be used in conjunction with these compression libraries; to have a small web server in front of the s3 dedicated for file compression. This wouldn't take too long to setup as I could re-purpose most of the code in the API.

**Comment by Nash0x7E2** [comment]
Yes, that would also help. I’ll dedicate some time this evening and tomorrow to look at both libs.

**Comment by orestesgaolin** [comment]
> Cool - another option which could be used in conjunction with these compression libraries; to have a small web server in front of the s3 dedicated for file compression. This wouldn't take too long to setup as I could re-purpose most of the code in the API.

That would be awesome. Perhaps could you also provide us with the thumbnail parameter in the API response? The images shown in the expressions list shouldn't be more than let's say 300x300 px JPEG with 80/90% compression ratio.
