### ISSUE TITLE
Flutter app performance

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#603]
App performance and speed seems a bit laggy. For example, clicking on notifications and navigating back has a slight delay. Viewing a photo and going back also crashes the app occasionally.

**Comment by orestesgaolin** [comment]
Will try to reproduce. What kind of phone do you own?

**Comment by Nash0x7E2** [comment]
Noted, can you send me some device and network info?

**Comment by sunyatax** [comment]
This was happening for @jdeepee as well. He has an android, not sure what kind. I have an iPhone 8 and this is on the current prod build.

**Comment by jdeepee** [comment]
I have a Google Pixel 2XL. This only became a problem recently and maybe seemed to get worse the more expressions reached the collective, although I cant be certain on that. 

I also experience an issue on s3 media loading. I load the collectives raw metadata; and then wait 5-10 seconds to load just one image from new expressions. Sometimes they will also be loaded and then "un-loaded" leaving me with a blank expression again.

Also noticed I seem to be fetching from the s3 for a few expressions everytime I open the app - they don't seem to cache. I can try and get some videos if that helps.

**Comment by Nash0x7E2** [comment]
Interesting, are you on the latest version of the app?

**Comment by sunyatax** [comment]
Nash, can you invite him to the dev build via codemagic? joshuadparkin@gmail.com

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Nash0x7E2** [comment]
Yes! Adding him now :)

**Comment by jdeepee** [comment]
Yeah using the latest production version

**Comment by sunyatax** [comment]
Wonder if occasional app crashes has to do with s3 as well? 

@orestesgaolin @Nash0x7E2

**Comment by Nash0x7E2** [comment]
I did not notice this while testing s3, no
