### ISSUE TITLE
Long network response times

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#604]
Often takes more than a few seconds to retrieve expressions or other responses from API.

**Comment by jdeepee** [comment]
Still yet to probe the AWS/Cloudflair infrastructure before requests reach our servers. But I just made a quick filter/scan over the http logs we have. Looking at only collective queries; most responses (90%+) are returned in 40-42ms. There is a few at around 80-90ms. And one at 150ms. 

I looked at around 500 responses by eye so take this with a grain of salt; there could be more variance but it should give us a general idea of how things are performing.

**Comment by Nash0x7E2** [comment]
It could also be due to the latency before the request hits the server and after a response is sent from the server. Feel like this is something we should test in a controlled environment.

**Comment by Nash0x7E2** [comment]
Can we close this @orestesgaolin @sunyatax ? The load time seems acceptable on the latest builds.

**Comment by sunyatax** [comment]
Yeah, we're also going to upgrade the API we're using in AWS so this should hopefully be resolved.

**Comment by Nash0x7E2** [comment]
Ok cool, closing.
