### ISSUE TITLE
Caching issue with notifications

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#617]
Looks like logging out and into another account shows notifications from the previous acc. May be a caching issue? @orestesgaolin

**Comment by Nash0x7E2** [comment]
@orestesgaolin could be that you're not clearing the box when the user logs out

**Comment by orestesgaolin** [comment]
Notifications were not stored in box, these are just IDs. This is more due
to local variable in in memoy in notification handler

Pozdrawiam,
Dominik Roszkowski

czw., 7 maj 2020, 03:48 użytkownik Neevash Ramdial <notifications@github.com>
napisał:

**Comment by Nash0x7E2** [comment]
Noted. Also noticed that all notifications disappear when I they are view, even if no action is taken.

In the case of connection and pack requests, would it be helpful to persist these notifications until an action is taken or they are manually cleared?

**Comment by orestesgaolin** [comment]
I'm working on caching them
