### ISSUE TITLE
Android app icon

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#637]
Using [flutter launcher icons ](https://pub.dev/packages/flutter_launcher_icons) for app icons. Works for iOS. Can one of you check android in latest dev build? @Nash0x7E2 @orestesgaolin

**Comment by Nash0x7E2** [comment]
Sure, I'll have a look in the morning.

**Comment by orestesgaolin** [comment]
This tool doesn't support flavors and IMHO is wrong approach to setting icons in native projects. It's better to do it in Android Studio and xcode.

**Comment by orestesgaolin** [comment]
I'll take care of that I just need the proper resolution of icon (1024x1024). Already asked on Slack.
