### ISSUE TITLE
Polish iOS and android splash screens

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#639]
Design better UI for this

**Comment by sunyatax** [comment]
Could one of you update the splash screens to the following? Let me know what type of assets you need from me. @Nash0x7E2 @orestesgaolin 

![junto_splash_screen](https://user-images.githubusercontent.com/37339459/82178248-2d933480-98a1-11ea-9d08-b50235709c35.png)

**Comment by orestesgaolin** [comment]
We would need:
- white logo on transparent background (around 800 px width or svg)
- gradient background (2436 x 1125 px minimum)

**Comment by sunyatax** [comment]
Let's just do the following instead: 

![junto_splash_screen_mockup](https://user-images.githubusercontent.com/37339459/82244478-ed669d00-9906-11ea-828f-4684cc0719b1.png)

**Comment by sunyatax** [comment]
Thanks for taking care of this @orestesgaolin - can we make the logo 1/3 smaller?

**Comment by orestesgaolin** [comment]
yup, of course
