### ISSUE TITLE
Visiting other people's packs

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#640]
Appbar + pack does not update sometimes when visiting other people's packs. @Nash0x7E2 can you look into this?

**Comment by sunyatax** [comment]
Please help test / resolve this @Nash0x7E2

**Comment by Nash0x7E2** [comment]
@sunyatax I am no longer experiencing this on the current build, ca we close this?

**Comment by sunyatax** [comment]
yep go for it

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
