### ISSUE TITLE
Account for empty spaces across app

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#641]
If text has a bunch of empty space with nothing after we should not display it.

We should also account for this in the API if not already (i.e. signing in with an email that has a blank space after used to not work) cc @jdeepee

**Comment by orestesgaolin** [comment]
In other words we should trim every user input in the app.

Best,
Dominik Roszkowski

niedz., 10 maj 2020, 00:53 użytkownik Eric <notifications@github.com>
napisał:

**Comment by jdeepee** [comment]
This now enforced on the backend. The only place where we do not trim incoming strings is on expression data; with the exception of expression channel data. Everywhere else incoming strings are trimmed.

**Comment by orestesgaolin** [comment]
Shall we abandon enforcing this on mobile inputs or just to be double-safe also trim inputs in the app?

**Comment by Nash0x7E2** [comment]
If this is enforced on the backend, then there is no need to enforce it on the app.
