### ISSUE TITLE
Two column layout persist across app + move to Hive

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#645]
Column setting does not persist across different feeds occasionally. Need to fix this + move over to hive instead of SharedPrefs

**Comment by Nash0x7E2** [comment]
@sunyatax Been looking at this and I am not able to reproduce this, are you still noticing it?

It appears to be working for @orestesgaolin as well

**Comment by sunyatax** [comment]
It’s working fine on simulator. Going to test this on latest dev build. Others on team have been experiencing this issue

**Comment by orestesgaolin** [comment]
There were some issues with accessing boxes differently across the app. The latest builds shouldn't have this issue, but maybe there are some spots left. In general we shouldn't access a given box in more than one place and some of them (the app box for instance) is being manipulated in a lot of places, sometimes directly in widgets.

**Comment by Nash0x7E2** [comment]
Cool, I am going to pull the latest CM build

**Comment by sunyatax** [comment]
Still running into an issue where there isn't one consistent layout across the app. For example, my Collective feeds are using two column but Den and Pack feeds are one column. It seems they are plugged into different states.
