### ISSUE TITLE
Don't show Flutter errors in alert dialogs

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#650]
Sometimes errors are shown as alert dialogs
![image](https://user-images.githubusercontent.com/16854239/81538362-f38cd480-936e-11ea-8f59-93b75f3e7030.png)

**Comment by Nash0x7E2** [comment]
We should be more careful when displaying errors in dialogs. Definitely don’t want to be leaking any DB urls  or keys
