### ISSUE TITLE
Signup process in welcome.dart is a buggy

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#651]
The `_handleSignUp` is too complex and causes some problems during sign up.

Sometimes it happens that 
- the process fails and user is not signed up
- the overlay throws exception
- the alert dialog with Provider error is shown (see below) (#652)
- the process finishes but user is not signed in afterwards (#653)

The overall process should be encapsulated either in userRepository, AuthBloc or somewhere else. It shouldn't be performed in state of Welcome page (see #583 )

Sample error:

```
flutter: 'package:provider/src/provider.dart': Failed assertion: line 193 pos 7: 'context.owner.debugBuilding || listen == false || _debugIsInInheritedProviderUpdate': Tried to listen to a value exposed with provider, from outside of the widget tree.
This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.
To fix, write:
Provider.of<UserDataProvider>(context, listen: false);
It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.
The context used was: Welcome(dirty, dependencies: [MediaQuery, _FocusMarker, _LocalizationsScope-[GlobalKey#0f647]], state: WelcomeState#12e37)
```

**Comment by Nash0x7E2** [comment]
Related: #583
