### ISSUE TITLE
User is not signed in after sign up

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#653]
After sign up user is not signed in, they land on Welcome page again.

After successful sign up user should be already logged in.

**Comment by Nash0x7E2** [comment]
Just noticed this on the latest dev. Will take care of this in the morning.

**Comment by sunyatax** [comment]
Important. Is this taken care of?

**Comment by sunyatax** [comment]
Seems there are two edge cases happening here:

1) User is reverting back to beginning of welcome flow on sign up (i.e., not signed in)
2) Nothing happens after submitting verification code, although an account is created. Only action available is pressing up on the screen before which says user is already created.

**Comment by orestesgaolin** [comment]
I haven't encountered the second issue. I'm looking into that now

**Comment by sunyatax** [comment]
May be worth fixing the 1st and seeing if the 2nd one persists

**Comment by orestesgaolin** [comment]
I'm on it

**Comment by orestesgaolin** [comment]
Well, I just encountered this second case where I was stuck on verification code

**Comment by orestesgaolin** [comment]
![image](https://user-images.githubusercontent.com/16854239/81864822-70859d00-956d-11ea-9bae-ebdc7297b0b0.png)
This may be related to this exception
