### ISSUE TITLE
Empty state for collective expressions

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#657]
It seems that we don't have an empty state for collective expressions. I wonder if we even need one, but letting you know

![image](https://user-images.githubusercontent.com/16854239/81540692-4c11a100-9372-11ea-87e3-b3e9315da490.png)

**Comment by Nash0x7E2** [comment]
cc: @sunyatax, related #343

**Comment by sunyatax** [comment]
Noted, thanks
