### ISSUE TITLE
Images reload on collective even though they are compressed

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#658]
It seems that compression is not enough to keep images from reloading and huge performance impact.

They are still in high resolution which may be a reason for reloads visible when returning from expression.

![RPReplay_Final1589231256](https://user-images.githubusercontent.com/16854239/81612318-eeff0500-93dc-11ea-8187-b57ddc0122a7.gif)

**Comment by sunyatax** [comment]
There were a couple of photos posted before we merged Nash's code. Let's have people delete them so we can be sure.

**Comment by orestesgaolin** [comment]
Some images even though they are compressed have size of 13 MB (whereas typically images from my camera are 4 MB). @Nash0x7E2 seems like compression doesn't work for them.

![image](https://user-images.githubusercontent.com/16854239/81680622-ae8e9e00-9453-11ea-8547-131705cbaa0f.png)

**Comment by orestesgaolin** [comment]
I just tried with new image on current build just to confirm and it's over 10 MB.

**Comment by orestesgaolin** [comment]
Hmm, seems like it wasn't the most recent version. After uninstalling and installing again it's around 400 kB which seems much more reasonable

**Comment by Nash0x7E2** [comment]
Maybe this is something we need to pass on to the rest of the team?

The app app should be completely uninstalled before installing the latest dev?

**Comment by orestesgaolin** [comment]
I doubt this is the reason for that. Maybe somehow the newest versions didn't get installed

**Comment by Nash0x7E2** [comment]
@orestesgaolin are you cropping the images?

**Comment by sunyatax** [comment]
We're also getting long wait times for posting (same for cropping as we discussed yesterday). Is this because of the compression that's taking place? @Nash0x7E2

**Comment by Nash0x7E2** [comment]
Yes, this could be a factor.

**Comment by orestesgaolin** [comment]
Compression takes less than half a second and the cropping time is around 5-10 seconds

**Comment by Nash0x7E2** [comment]
Going to ping @slightfoot on this.

**Comment by sunyatax** [comment]
Cropping takes place before we post the expression though, and we're getting long wait times on creation as well. Seems like two separate issues?

**Comment by Nash0x7E2** [comment]
Can we close this @orestesgaolin @sunyatax? I am pretty happy with the server load times, they are within an acceptable range

**Comment by orestesgaolin** [comment]
We're going to track image perf improvements in separate task maybe related to server side thumbnail generation
