### ISSUE TITLE
Update of CachedNetworkImage

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#662]
We're still using our fork of CNI https://github.com/juntofoundation/flutter_cached_network_image that's from March and in April there were some serious changes in CNI and cache_manager.

I know that we forked this because S3 presigned urls were problematic, but maybe we can reconsider our approach and instead of forking the library, provide custom base cache manager like proposed in issue 175 of flutter_cached_network_image.

https://pub.dev/packages/cached_network_image#-changelog-tab-
https://pub.dev/packages/flutter_cache_manager#-changelog-tab-

**Comment by Nash0x7E2** [comment]
This seems promising, I'll look into this further sometime this week and next.
