### ISSUE TITLE
Occasional error fetching notifications

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#666]
Getting a 500 here and there. @orestesgaolin @Nash0x7E2 are you guys experiencing this too? Maybe it's something server-side? @jdeepee 

`flutter: [DEBUG] [_RouteEntry.handlePop]: pop null from JuntoCollective
flutter: [DEBUG] [_RouteEntry.handlePush]: push notifications from JuntoCollective
flutter: [NotificationNavigationObserver.didPush]: fetching notifications
flutter: [NotificationRepo.getJuntoNotifications]: Fetching notifications from API
flutter: [ERROR] [NotificationRepo.getJuntoNotifications]: Error while fetching notifications due to Internal Server Error 500
flutter: [ERROR] [NotificationsHandler.fetchNotifications]: Couldn't retrieve notifications from cache
flutter: [ERROR] [NotificationNavigationObserver.didPush]: Couldn't fetch the notifications
flutter: [DEBUG] [_RouteEntry.handlePop]: pop notifications from JuntoCollective
flutter: [NotificationNavigationObserver.didPop]: fetching notifications
flutter: [NotificationRepo.getJuntoNotifications]: Fetching notifications from API
flutter: [DEBUG] [_RouteEntry.handlePop]: Marking notifications as read because popping from notifications screen
flutter: [ERROR] [NotificationRepo.getJuntoNotifications]: Error while fetching notifications due to Internal Server Error 500
flutter: [ERROR] [NotificationsHandler.fetchNotifications]: Couldn't retrieve notifications from cache
flutter: [ERROR] [NotificationNavigationObserver.didPop]: Couldn't fetch the notifications`

**Comment by Nash0x7E2** [comment]
Looking at this now

**Comment by jdeepee** [comment]
I am seeing 500 errors related to the serialization of comment notifications. This is probably what is causing the error. I have a feeling this might be caused by the server trying to grab old comments using the old notification database structure. Do you know if you were successfully getting comments before this started happening?
