### ISSUE TITLE
Inconsistent theme in welcome

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#668]
When logging out, themes are sometimes inconsistent. For example, there could be a rainbow gradient background with a button that uses the accentColor of the Royal theme. When people log out we may need to do a full refresh to rainbow. @Nash0x7E2

**Comment by Nash0x7E2** [comment]
When users log out, their information is deleted so all preferences would also be deleted. In this case, the screen they see would be using the default theme

**Comment by sunyatax** [comment]
Right, but there's a bug where the theme it's pulling from is actually not the default rainbow one. It's still using an accent color from another theme.

**Comment by Nash0x7E2** [comment]
Noted, will have a look at it

**Comment by orestesgaolin** [comment]
Yeah, the information about theme removal is not propagated immadiately, that's why some screens (welcome in particular) don't know that they have to be updated
