### ISSUE TITLE
Reset notification cache

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#679]
Need to reset notification cache when accepting/declining connection or pack requests

**Comment by orestesgaolin** [comment]
What do you mean by "resetting" the cache? Do you mean that these particular notifications should be removed? Maybe you can filter them by some kind of flag (e.g. hidden)?

**Comment by sunyatax** [comment]
Accepting or declining a request deletes the notification in the API. However, the requests are still being shown client side and aren't updated properly. I suspect this has to do with caching?

**Comment by sunyatax** [comment]
To test, send yourself a connection request between two of your dev accs and try to accept. It successfully creates the connection and removes the notification from the database, but does not update until I log out of the account and log back in.

**Comment by orestesgaolin** [comment]
Yup, we only "add" to cache, not remove. We would have to handle this separately. If we remove all notifications from cache, then we have to somehow keep the "unread" status. So the only solution right now would be to delete them selectively.

**Comment by sunyatax** [comment]
This works fine for connection and pack requests. What about for all the comment notifications that are deleted when a user deletes their expression? In our current implementation, it seems we will have to go in and delete each one of those too.
