### ISSUE TITLE
Sign up doesn't nav to community agreements

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#691]
Tested this on latest dev, the version before my PR 'Merge pull request #686 from juntofoundation/fix/sign-up-image-selection'(tree 689257eaa6) and an even earlier version 'Refactor selecting and cropping of profile picture during sign up' (ffabb357a9), and navigation to community agreements post-sign up aren't working there. Maybe this was taken care of in Nash's performance PR? Either way, I remember it working at one point, but it's no longer functional.

cc @orestesgaolin

**Comment by orestesgaolin** [comment]
Does it navigate to Lotus or is stuck on loading page?

sob., 16 maj 2020, 04:13 użytkownik Eric <notifications@github.com> napisał:

**Comment by orestesgaolin** [comment]
Interesting error that may be a reason for that 
![image](https://user-images.githubusercontent.com/16854239/82122122-ed915c00-9791-11ea-8549-5f60cc82fad0.png)

**Comment by sunyatax** [comment]
Yeah.. are you in the latest de? I'm not getting that error / fixed that in my notifications PR.

This is my log during the sign up flow. Below is a screenshot of the screen I'm stalled on as well.

`flutter: 1
flutter: 2
flutter: {username: eyango}
flutter: 200
flutter: {"valid_username":true}
flutter: 200
flutter: 3
flutter: 4
flutter: 5
flutter: 6
flutter: [DEBUG] [WelcomeState._nextSignUpPage]: Verifying e-mail
flutter: [DEBUG] [AuthRepo.verifyEmail]: {email: eric.yang217+2@gmail.com}
flutter: [DEBUG] [AuthRepo.verifyEmail]: 200 {"message":"You registration is nearly complete. Please check your email for a verification code sent by hi@junto.foundation"}
flutter: [DEBUG] [GestureRecognizer.invokeCallback]: You registration is nearly complete. Please check your email for a verification code sent by hi@junto.foundation
flutter: 7
flutter: [AuthBloc.mapEventToState]: User signed up
flutter: [DEBUG] [AuthBloc._mapSignUpEventState]: Registering user
flutter: [DEBUG] [AuthRepo.registerUser]: {"private_den":{"address":"52b90fc3-d82e-277c-6fc2-ea2806d5864b","name":"Eyango's Private Den","creator":"82b90fc3-d828-5fd9-bea5-b71e62b5c630","privacy":"Private","is_default":true,"created_at":"2020-05-16T22:08:05Z"},"public_den":{"address":"f0b90fc3-d82f-6089-9d30-23cbdb317688","name":"Eyango's Den","creator":"82b90fc3-d828-5fd9-bea5-b71e62b5c630","privacy":"Public","is_default":true,"created_at":"2020-05-16T22:08:05Z"},"pack":{"address":"52b90fc3-d82f-87ad-928e-eb82271987b4","creator":"82b90fc3-d828-5fd9-bea5-b71e62b5c630","created_at":"2020-05-16T22:08:05Z","privacy":"Private","group_type":"Pack","group_data":{"name":"Eyango's Pack"}},"user":{"address":"82b90fc3-d828-5fd9-bea5-b71e62b5c630","email":"eric.yang217+2@gmail.com","username":"eyango","bio":"","name":"Eyango","created_at":"2020-05-16T22:08:05Z","profile_picture":[],"gender":[""],"location":[""],"website":[""],"background_photo":""},"user_perspective":{"address":"ccb90fc3-d830-5d30-adf2-17<…>
flutter: [AuthRepo.registerUser]: Logging in user
flutter: [AuthRepo.registerUser]: User logged in
flutter: [AuthRepo.registerUser]: Storing user data
flutter: [UserDataProvider.initialize]: Fetching user information`

![Simulator Screen Shot - iPhone X - 2020-05-16 at 17 08 13](https://user-images.githubusercontent.com/37339459/82131184-04d34800-9798-11ea-83ab-0f35335a7249.png)

**Comment by sunyatax** [comment]
Last bug we need to resolve before moving into external testing. Would be great if you could resolve this @orestesgaolin ; thanks

**Comment by orestesgaolin** [comment]
I'm on it today
