### ISSUE TITLE
Floating appbar in NestedScrollView

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#700]
Doesn't seem like this is possible right now ([flutter #17518](https://github.com/flutter/flutter/issues/17518)). Bookmarking this to review later and explore hacky alternatives. Have only been able to produce the desired result within a CustomScrollView, but that leaves several possibilities of TabBar + refreshing only the feed out of the picture.

**Comment by Nash0x7E2** [comment]
I'll keep an eye on this issue. After looking at it, the issue was added to the May 2020 milestone so hopefully, this would be resolved soon
