### ISSUE TITLE
Various notification caching optimizations

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#701]
So, when you receive a pack request you will get both a connection and a pack request notification in your inbox. What we have set up right now is that responding to one of those requests deletes only that particular notification from cache. However, in the case of the pack request, if I accept it *before* I respond to the connection request, it removes both of them from the API (since joining someone's pack automatically connects you with them). The issue we have then is that the connection request remains in cache as only the pack request in removed. 

Would it be better for us to simply have one 'update notification cache' function to use? @orestesgaolin I know you're working on this for removing comment notifications, and I wonder if we should just implement this for all areas that need to update cache to reduce the amount of edge cases we need to account for and ensure we're always up to date with what the API returns. We won't ever have more than 100 notifs so I don't think it would be a big performance issue.

@Nash0x7E2 if this is the route we take then we could just implement this function when responding to requests in the relations drawer + packs requests in the Packs section of the app.

**Comment by orestesgaolin** [comment]
> I wonder if we should just implement this for all areas that need to update cache to reduce the amount

yeah, I think that we just need to handle "general case", I'm on it but got distracted by some side quests like image cropping


Will handle this tomorrow
