### ISSUE TITLE
Need to handle error message on sign up

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#705]
_handleSignUp in welcome.dart should show a SingleActionDialog with an error message when something goes wrong. Right now, it just navigates back to the welcome screen. 

Looked at the code briefly and was unsure how to perform this within the context of using context.bloc<AuthBloc>().add implementation as the event is handled within the AuthBloc and _mapSignUpEventState requires a yield of Stream<AuthState>. Could you tackle this?

@orestesgaolin 

-- type of dialog we need below --
```
      showDialog(
        context: context,
        builder: (BuildContext context) => SingleActionDialog(
          dialogText: error.message
        ),
      );
```

**Comment by orestesgaolin** [comment]
I'm on it

**Comment by orestesgaolin** [comment]
@sunyatax any particular kind of error?
