### ISSUE TITLE
Test app with new version of CachedNetworkImage

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#713]
CNI released new version based on Octoimage

We should check out if the update is going to influence the performance and stability of the app

https://pub.dev/packages/cached_network_image/versions/2.3.0-beta

**Comment by Nash0x7E2** [comment]
Adding this to my tasks for the week.

**Comment by orestesgaolin** [comment]
Let's close this for now and revisit later
