### ISSUE TITLE
Remove localstorage dependency

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#714]
It looks like we have dependency on localstorage package and the only place where we use it is in the `readLocalUser` method of `UserService`.

This method is never used in the app.

Shall we remove it entirely or replace with Hive? 

![image](https://user-images.githubusercontent.com/16854239/82537022-acaa9600-9b49-11ea-972e-3e52a3e3cf08.png)

**Comment by Nash0x7E2** [comment]
In progress with #719
