### ISSUE TITLE
Consider removing slidable dependency

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#715]
The only place where we use slidable is in perspective_item.dart but because the Perspectives page allows to open right drawer it's impossible to use slidable there.

We have to either enable sliding again or remove it entirely.
![image](https://user-images.githubusercontent.com/16854239/82537304-1aef5880-9b4a-11ea-9ea3-010f04fe284e.png)

**Comment by sunyatax** [comment]
The slideable works, even though there's a right drawer. I intentionally only enabled it for custom perspectives, not the default ones.

**Comment by orestesgaolin** [comment]
Oh, that's cool! I only checked on the default ones.
