### ISSUE TITLE
Team testing issue

### ISSUE THREAD

**Issue by dr-drea** [juntofoundation/junto-mobile#718]
beep bop boop lalalalala @orestesgaolin 
![when-you-remember-to-bring-your-reusable-bag-to-the-grocery-store-arnold-schwarzenegger-with-animals](https://user-images.githubusercontent.com/41347702/82679944-9f5cdc80-9c19-11ea-97b1-40ed34ad313e.jpg)

**Comment by Nash0x7E2** [comment]
👀👀

**Comment by orestesgaolin** [comment]
Thanks @dr-drea for the issue!

**Comment by doraliliom** [comment]
Hello issue

**Comment by orestesgaolin** [comment]
Nice to see you here

**Comment by dr-drea** [comment]
hmmmmmm
