### ISSUE TITLE
Cannot open dialog to invite/subscribe

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#735]
In current build:
1. Sign up
2. Go to someone's profile
3. Tap on the infinity icon
4. The white overlay is shown but nothing else

**Comment by sunyatax** [comment]
Strange, I'm not running into this issue. Anyone else? @jdeepee @Nash0x7E2

**Comment by Nash0x7E2** [comment]
I am not seeing this on my branch but I may need to pull and try again

**Comment by orestesgaolin** [comment]
I will look into that

**Comment by orestesgaolin** [comment]
Hmmm, doesn't occur any more :/
