### ISSUE TITLE
Enable swipe back on collective + packs page views

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#742]
WiIl need to disable swipe for filter channel - not sure if it's possible in our current implementation to only disable swipe to filter but keep swipe for end drawer? @orestesgaolin

**Comment by orestesgaolin** [comment]
Yeah, let me fix that

**Comment by orestesgaolin** [comment]
Should swipe on collective navigate back to the perspectives list?

**Comment by sunyatax** [comment]
Yep, exactly. Are you just configuring a way to dynamically enable/disable swipe to filter drawer? That would be the best solution as there are instances in the app (I.e Den) where we do want swipe to be available

**Comment by orestesgaolin** [comment]
I can try to do that. The problem is that we have a PageView underneath and even with ClampingScrollPhysic the behavior is far from ideal

**Comment by sunyatax** [comment]
I see. Maybe what we want is to detect a horizontal swipe to the right and use the page controller to jump back to the first page, so the animation of going to the feed and navigating back are the same.

**Comment by orestesgaolin** [comment]
I can't seem to find a way right now to achieve what you wish for.

I fear that it would require a bit of rework :/

**Comment by sunyatax** [comment]
You mean specifically disabling swipe for only the drawer?

**Comment by orestesgaolin** [comment]
Returning the issue to you @sunyatax :)
