### ISSUE TITLE
when clicking on a perspective and then clicking on channel search, when swiping out of channel search, the swipe animation doesn’t take you all the way back it stops halfway

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#759]
![image](https://user-images.githubusercontent.com/65966547/83150409-3d90ec80-a0c9-11ea-9ecb-05501f668abb.png)

**Comment by Nash0x7E2** [comment]
@orestesgaolin can this be filter drawer related?

**Comment by orestesgaolin** [comment]
Yeah, @sunyatax and I added the workaround that didn't work
