### ISSUE TITLE
Choosing Themes Buzz Indicator

### ISSUE THREAD

**Issue by doraliliom** [juntofoundation/junto-mobile#767]
When choosing themes, there used to be a small vibration to indicate choice. Now missing. I'd also be okay with just a border showing choice.

**Comment by orestesgaolin** [comment]
@sunyatax have you disabled it?

**Comment by sunyatax** [comment]
No, it’s working for me

**Comment by orestesgaolin** [comment]
Working for me too...

**Comment by Nash0x7E2** [comment]
Work for me on the latest build
