### ISSUE TITLE
Warning when leaving expression create page

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#781]
When you're creating an expression and then click on the lotus, the expression you're working on is deleted - need to notify the user that this will happen ("are you sure you want to leave? your expression will be deleted") OR save the status of the expression so when you go back into expression center and click on an expression type, the last thing you were typing/creating is still there

**Comment by orestesgaolin** [comment]
Hi @yaz38 I moved the long title to the description and made the title a bit more clear. Thanks for letting us know
