### ISSUE TITLE
While sharing an audio expression - took about 10 seconds of loading to share

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#803]

**Comment by Nash0x7E2** [comment]
This can be due to network speed, latency, etc. I'll have a look at posting an audio expression to verify it's not something app side.

**Comment by Nash0x7E2** [comment]
@yaz38 How long was the audio? The longer the audio the larger the file size which in turn would affect the upload time.

**Comment by yaz38** [comment]
1 min 30ish seconds and the other was 2 min

**Comment by Nash0x7E2** [comment]
Cool, will try to reproduce :+1

**Comment by Nash0x7E2** [comment]
I am closing this for now. After testing, audio expressions are being uploaded within a reasonable time period.
