### ISSUE TITLE
Perspectives UX

### ISSUE THREAD

**Issue by tomisparker** [juntofoundation/junto-mobile#812]
We need to create UX improvements to be able to add people to perspectives from an expression or their Den or the members search.

**Comment by Nash0x7E2** [comment]
Is there a spec or wireframe for what this should look like?

**Comment by tomisparker** [comment]
I would check with Eric-
We briefly talked about adding a "add to Perspectives" option that would
replace the Subscribe checkbox under the infinity symbol on a person's
profile.

**Comment by sunyatax** [comment]
I'll take care of this
