### ISSUE TITLE
Regarding commenting on a comment

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#829]
Change title “Expression Comment” to “Comment”

Need a way to access the original comment thread and the original expression, right now you can only see your own comment thread and it doesn’t link you back to the expression - would be good if you could swipe back ?

Additionally, when you look at the original comment thread - it should indicate somehow that there are responses to that comment- a comment thread has begun: example is where Eric responded to Yaz’s comment on Drea’s “is pop music bad” expression

![image](https://user-images.githubusercontent.com/65966547/84192279-c0ba2700-aa67-11ea-96c0-3123050cf5b5.png)

**Comment by sunyatax** [comment]
Yep, those things are in motion.

Also, there aren't any titles anymore for comments so you won't see Expression Comment or comment

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
