### ISSUE TITLE
[Cognito] missing points and bugs

### ISSUE THREAD

**Issue by orestesgaolin** [juntofoundation/junto-mobile#840]
- [x] delete account not working
- [x] wrong password or username while sign in not handled properly
- [x] crash when resetting the password on iOS
- [x] Created at date should be returned as part of the user object
- [ ] While creating an account, there was a moment where the app hanged and showed a blank screen at stage four
- [x] null reference on Android
- [x] putting in the verification code it tells me its wrong but then continued with the registration no problem
- [x] Let's change email from no-reply@verificationemail to hi@junto.foundation (@jdeepee)
- [x] issue when verification code is not sent #859

**Comment by Nash0x7E2** [comment]
- [ ] Created at date should be returned as part of the user object
- [ ] While creating an account, there was a moment where the app hanged and showed a blank screen at stage four

**Comment by jdeepee** [comment]
When putting in the verification code it tells me its wrong but then continued with the registration no problem

**Comment by orestesgaolin** [comment]
I submitted bug report to Cognito team because we're getting null references in release mode that I cannot link to anything in plugin or our code https://github.com/aws-amplify/aws-sdk-android/issues/1879

**Comment by orestesgaolin** [comment]
Seems like the issue was related to missing proguard rules

**Comment by sunyatax** [comment]
Was able to create an account pretty smoothly...

- [ ] Let's change email from no-reply@verificationemail to hi@junto.foundation

**Comment by orestesgaolin** [comment]
@jdeepee please check with the newest build (idx 252) if the issue with verification code persists)

**Comment by sunyatax** [comment]
- [ ] Uploading prof pic during sign up flow doesn't change state correctly. Text/functionality still remains as 'Profile Picture' instead of 'Remove Photo' - only changes when going to next/prev page and revisiting. 

- [ ] Occasionally running into instances where About section is completely blank. Photo below.

@Nash0x7E2 can you see what's going on?

![Simulator Screen Shot - iPhone X - 2020-06-16 at 17 42 05](https://user-images.githubusercontent.com/37339459/84831151-d1831380-aff8-11ea-870e-5db9a08eab5b.png)

**Comment by jdeepee** [comment]
> Was able to create an account pretty smoothly...
> 
>     * [ ]  Let's change email from no-reply@verificationemail to [hi@junto.foundation](mailto:hi@junto.foundation)

This is now done; let me know if you want to change the text in the email or use some custom HTML/CSS.

**Comment by Nash0x7E2** [comment]
We may need to call `logout` after resetting the user password
```
PlatformException(Error, Error signing in, There is already a user which is signed in. Please log out the user before calling showSignIn.)
```
