### ISSUE TITLE
Photo Expression Opening with a Pulse-like Effect

### ISSUE THREAD

**Issue by doraliliom** [juntofoundation/junto-mobile#885]
When you click on a photo preview to open it, it opens and has an immediate, short & subtle pulse-like effect. (May be related: in the past, the issue was that it quickly flashed the open expression in the size of the preview and then automatically resized it. Not able to attach mp4 file to illustrate.)

**Comment by sunyatax** [comment]
Is this still happening? @doraliliom

**Comment by doraliliom** [comment]
Yes.
