### ISSUE TITLE
Check server version and force update

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#888]
@Nash0x7E2 can you take care of this?

**Comment by Nash0x7E2** [comment]
Sure I can look into this. Do we want to include this in today’s update or can this wait for our next release?

**Comment by sunyatax** [comment]
Wait for next release. Let's just resolve Hive issue and get the next build up for review today.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sunyatax** [comment]
Let's revisit this soon @Nash0x7E2
