### ISSUE TITLE
Kickstarter badges

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#905]
We'll need to build this to fulfill our Kickstarter tier / acknowledgements

**Comment by Nash0x7E2** [comment]
Perhaps we could store this information as part of the user profile then conditionally display a badge on the front end.

Maybe something like: 
```dart
User(
type: "kickstarter", // Other possible values could be "verified", "regular", etc 
)
```

Then in our frontend
```dart
if(user.type == "kickstarter"){
  showJuntoBadge();
}
```
