### ISSUE TITLE
Pagination doesn’t work after the 1st time

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#945]
@Nash0x7E2 v importante. Please assist

**Comment by Nash0x7E2** [comment]
Strange, I just tried reproducing on the latest prod build. Will have a patch ready tomorrow 💪

**Comment by sunyatax** [comment]
Awesome. Are you running into it as well, or is it just me?

**Comment by Nash0x7E2** [comment]
Closing
