### ISSUE TITLE
bug - switching from night to light theme

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#994]
(the header background is still in night theme)

![image](https://user-images.githubusercontent.com/65966547/89223628-1a8d2800-d5a5-11ea-9082-b43dd0558634.jpeg)

**Comment by sunyatax** [comment]
See if he's on the latest build and what Theme he's using (ie. Rainbow, sand, etc.) - hard to know what's going on otherwise @yaz38
